version: '3'

services:
  mlenv:
    image: mlenv
    container_name: mlenv
    hostname: mlenv
    network_mode: 'host'
    # ports:
      # - '8888:8888'
    volumes:
      - ./share:/root/share
      - ./.ssh:/root/.ssh
    privileged: true
    restart: always
